config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin, path: Spree.admin_path do
    resources :yml_codes
    resources :stalnoy_imports
    get '/stalnoy_import_test', to: 'stalnoy_imports#test'
    get '/stalnoy_import_rules', to: 'stalnoy_imports#rules'
    get '/stalnoy_import_upload', to: 'stalnoy_imports#upload'
    get '/stalnoy_import_cols/:id', to: 'stalnoy_imports#cols', as: 'vcols'
    get '/stalnoy_import_rows/:id', to: 'stalnoy_imports#rows', as: 'vrows'
    match  '/stalnoy_import_setcols/:id', to: 'stalnoy_imports#setcols', as: 'setcols', via: [ :put, :pach]
    match  '/stalnoy_import_setrows/:id', to: 'stalnoy_imports#setrows', as: 'setrows', via: [ :put, :pach]
    get '/stalnoy_import_test_stream', to: 'stalnoy_imports#test_stream'
    get '/stalnoy_import_stream/:id', to: 'stalnoy_imports#stream', as: 'streamid'
    get '/stalnoy_import_hide_all', to: 'stalnoy_imports#hide_all'

    get '/yml_code/:id', to: 'yml_codes#start', as: 'priceid'

  end
end

app/models/spree/stalnoy_import.rb
module Spree
  class StalnoyImport < ApplicationRecord

  end
end

app/controllers/spree/admin/stalnoy_imports_controller.rb
module Spree
  module Admin
    class StalnoyImportsController < ResourceController

      include ActionController::Live

      def edit
        Spree::StalnoyImport.find(params[:id]).update(last_row: nil, data_prepared: nil)
      end

      def test_stream
        response.headers['Content-Type'] = 'text/event-stream'
        10.times {|n|
          response.stream.write "data: #{n}...\n\n"
          sleep 1
        }

      rescue IOError, ActionController::Live::ClientDisconnected
        logger.info "Stream closed"
      ensure
        response.stream.close
      end

      def stream
        response.headers['Content-Type'] = 'text/event-stream'
        @vendor = Spree::StalnoyImport.find(params[:id])

        if @vendor.data_prepared.nil?
          StalnoyImport.uncached do
            response.stream.write "data: #{Hash['status' => 'preparing'].to_json}\n\n"
            @rules = JSON.parse @vendor.rows
            @ruls_item_code = StalnoyRules.rules_parse(@vendor.rows, "item_code")
            @ruls_price = StalnoyRules.rules_parse(@vendor.rows, "price")
            @ruls_available = StalnoyRules.rules_parse(@vendor.rows, "available")
            @ruls_unavailable = StalnoyRules.rules_parse(@vendor.rows, "unavailable")
            @ruls_on_order = StalnoyRules.rules_parse(@vendor.rows, "on_order")
            @data = ActiveSupport::JSON.decode(@vendor.data).to_a[0][1] if Spree::StalnoyImport.exists?(params[:id])
            @preset = []
            @template = ActiveSupport::JSON.decode(@vendor.cols)
            @data.count.times do |i|
              item_code_current_value = @data[i][@template["item_code"].to_i]
              price_current_value = (@rules["white_space"] == 'true') ? @data[i][@template["price"].to_i].to_s.sub(',', '').to_f : (@rules["white_space"] == 'false') ? @data[i][@template["price"].to_i].to_s.sub(',', '.').to_f : @data[i][@template["price"].to_i].to_f
              available_current_value = @data[i][@template["available"].to_i]

              if StalnoyRules.bool_and(@ruls_item_code, item_code_current_value) and StalnoyRules.bool_and(@ruls_price, price_current_value) and (StalnoyRules.bool_or(@ruls_available, available_current_value) or StalnoyRules.bool_or(@ruls_on_order, available_current_value) or StalnoyRules.bool_or(@ruls_unavailable, available_current_value))
                @preset << [
                    item_code_current_value,
                    price_current_value,
                    available_current_value
                ]
                response.stream.write "data: #{Hash['status' => 'preparing',
                                                    'total' => @data.count,
                                                    'last_row' => i + 1,
                                                    'item_code' => item_code_current_value,
                                                    'price' => price_current_value,
                                                    'id' => params[:id]].to_json}\n\n"
              else
                response.stream.write "data: #{Hash['status' => 'preparing',
                                                    'total' => @data.count,
                                                    'last_row' => i + 1,
                                                    'item_code' => item_code_current_value,
                                                    'state' => 'error',
                                                    'id' => params[:id]].to_json}\n\n"
              end

            end
            @vendor.update(data_prepared: @preset.to_json)
          end
          @vendor = Spree::StalnoyImport.find(params[:id])
        end


        # if @vendor.last_row.nil?
        #   @count = ActiveSupport::JSON.decode(@vendor.data_prepared).count
        #   @count += 1;
        #   response.stream.write "data: #{Hash['status'=> 'nil_last_row','count' => @count].to_json}\n\n"
        # end

        unless params[:id].nil?
          @count = ActiveSupport::JSON.decode(@vendor.data_prepared).length
          # @count += 1;
          last_row = (@vendor.last_row.nil?) ? 0 : @vendor.last_row
          if @count > last_row
            i = 0;
            data = ActiveSupport::JSON.decode(@vendor.data_prepared).to_a
            data.each_with_index do |row, index|
              if @vendor.last_row.to_i > index
                next
              end

              variant = Spree::Variant.find_by(sku: row[0])
              
              if !variant.nil?
                old_price = variant.price
                currency = JSON.parse(@vendor.cols)["currency"]
                available_was = variant.backorderable?
                available_now = StalnoyRules.bool_or(@ruls_available, row[2])

                if (currency == '$SOURCE' or currency == nil or currency == '')
                  Spree::Variant.find_by(sku: row[0]).update(cost_price: row[1].to_f)
                else
                  Spree::Variant.find_by(sku: row[0]).update(cost_price: row[1].to_f, cost_currency: currency)
                end
                
                Spree::Variant.find_by(sku: row[0]).stock_items.update(backorderable: available_now)
                
                
                  Spree::Product.find_by(id: variant.product_id).update(discontinue_on: Time.now + 14.day)
                
                response.stream.write "data: #{Hash['status' => 'work',
                                                    'total' => @count,
                                                    'last_row' => index + 1,
                                                    'id' => params[:id],
                                                    'vendor' => @vendor.name,
                                                    'currency' => currency,
                                                    'item_code' => row[0],
                                                    'price' => row[1],
                                                    'old_price' => old_price,
                                                    'available_status_now' => available_now,
                                                    'available_status_before' => available_was
                ].to_json}\n\n"
                else
                response.stream.write "data: #{Hash['status' => 'work',
                                                    'total' => @count,
                                                    'last_row' => index + 1,
                                                    'id' => params[:id],
                                                    'vendor' => @vendor.name
                ].to_json}\n\n"
              end

              if i >= 10
                @vendor.update(last_row: index)
                i = 0
              end


              i += 1
            end
            @vendor.update(last_row: @count)
            response.stream.write "data: #{Hash['status' => 'done',
                                                'total' => @count,
                                                'last_row' => @vendor.last_row,
                                                'id' => params[:id],
                                                'vendor' => @vendor.name
            ].to_json}\n\n"
          else
            response.stream.write "data: #{Hash['status' => 'done',
                                                'total' => @count,
                                                'last_row' => @vendor.last_row,
                                                'id' => params[:id],
                                                'vendor' => @vendor.name
            ].to_json}\n\n"
          end


        end


      rescue IOError, ActionController::Live::ClientDisconnected
        logger.info "Stream closed"
      ensure
        response.stream.close
      end


      def upload
        @stalnoy_imports = Spree::StalnoyImport.order('id ASC')

      end


      def index
        @stalnoy_imports = Spree::StalnoyImport.order('id ASC')
      end


      def rules
        @test = "hello"
        @stalnoy_imports = Spree::StalnoyImport.all

      end

      def rows
        @vendor = Spree::StalnoyImport.find(params[:id])
        @data = ActiveSupport::JSON.decode(@vendor.data).to_a[0][1] if Spree::StalnoyImport.exists?(params[:id])
        @preset = []
        @template = ActiveSupport::JSON.decode(@vendor.cols)
        if params[:size] == 'all'
          @data.each_with_index do |val, i|
            @preset << [
                @data[i][@template["item_code"].to_i],
                (@data[i][@template["price"].to_i].nil?) ? '' : @data[i][@template["price"].to_i].delete(',').to_f,
                @data[i][@template["available"].to_i]
            ]
          end
        else
          ((params[:size] != nil) ? params[:size].to_i : 50).times do |i|

            @preset << [
                @data[i][@template["item_code"].to_i],
                (@data[i][@template["price"].to_i].nil?) ? '' : @data[i][@template["price"].to_i].delete(',').to_f,
                @data[i][@template["available"].to_i]
            ]
          end
        end


        if @vendor.rows != nil


          @ruls_item_code = StalnoyRules.rules_parse(@vendor.rows, "item_code")
          @ruls_price = StalnoyRules.rules_parse(@vendor.rows, "price")
          @ruls_available = StalnoyRules.rules_parse(@vendor.rows, "available")
          @ruls_unavailable = StalnoyRules.rules_parse(@vendor.rows, "unavailable")
          @ruls_on_order = StalnoyRules.rules_parse(@vendor.rows, "on_order")
          @rules = JSON.parse @vendor.rows
        else
          @rules = Hash["item_code" => "!=:nil", "price" => "<:0", "available" => "nil", "unavailable" => "nil", "on_order" => "nil", "white_space" => "false"]
        end


        ((params[:size] != nil) ? params[:size].to_i : 50).times do |i|

          @preset << [
              @data[i][@template["item_code"].to_i],

app/views/spree/admin/stalnoy_imports/edit.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:edit_vendor, scope: :stalnoy_import) %>
<% end %>

<%= render 'form', resource: @stalnoy_import %>

app/views/spree/admin/stalnoy_imports/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:import, scope: :stalnoy_import) %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:yml_code, scope: :stalnoy_import), admin_yml_codes_path, icon: 'share-alt', class: 'btn-success' %>
      <%= button_tag(nil, class: 'btn red-b btn-sm btn-danger hash-event',action: 'put', hash: 0, key: 'hide_all') do %>
      <%= content_tag(:span,nil, class: 'icon icon-circle-arrow-up') %>
      <%= Spree.t(:hide_all, scope: :stalnoy_import) %>
      <% end %>
    <%= button_link_to Spree.t(:test, scope: :stalnoy_import), admin_stalnoy_import_test_path, icon: 'flag', class: 'btn-primary', id: 'admin_stalnoy_import_test' %>
    <%= button_link_to Spree.t(:new_vendor, scope: :stalnoy_import), new_object_url, icon: 'plus', class: 'btn-primary', id: 'admin_new_stalnoy_import' %>
    <% if @stalnoy_imports.any? %>
        <%= button_link_to Spree.t(:setup_rules, scope: :stalnoy_import), admin_stalnoy_import_rules_path, icon: 'th-list', class: 'btn-danger' %>
        <%= button_link_to Spree.t(:update, scope: :stalnoy_import), admin_stalnoy_import_upload_path, icon: 'refresh', class: 'btn-success' %>
    <% end %>

<% end %>
<% content_for :head do %>
   <style>
    .progress-bar-warning {
      background-color: #478dc1;
    }
    .progress {
      position: relative;
      height: 40px;
      margin-bottom: 0;
    }
    .progress-bar{
      position: relative;
      top: 20px;
      height: 50%;
    }
    .index {
      z-index: 2;
      width: 100%;
      display: block;
      position: absolute;
      text-align: center;
    }
    th,.center {
      text-align: center;
    }
    .red_b{
      width: 34px;

    }
    .green-b
    {
      width: calc(100% - 42px);
    }
    .modal-dialog {
      width: 80%;
    }

  </style>
<% end %>
<div class="progress" hash="0" id="progress-bar">
  <%# last_row= (import.last_row.nil?)? 0 : import.last_row.to_i + 1%>
  <%# total = (import.data_prepared.nil?)? 0 : ActiveSupport::JSON.decode(import.data_prepared).count + 1%>
  <%# progress = (last_row == 0 && total == 0)? 100 : last_row / total.to_f*100 %>
  <% last_row= 0 %>
  <% total = Spree::Product.where(discontinue_on: Time.now..Time.now + 14.day).count %>
  <% progress = 0  %>
  <span class="index" id="p-content-0">[ <%= last_row %> / <%=total%> ]  <%= progress.to_s[0..5] %>% <%= Spree.t(:hide_all, scope: :stalnoy_import) %> <%= (last_row != 0 && total != 0 && progress == 100 )? Spree.t(:updated, scope: :stalnoy_import) : Spree.t(:ready, scope: :stalnoy_import) %> </span>


  <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:0%" id="hash-bar-0"></div>
</div>
<table class="table">
  <thead>

  <th><%= Spree.t(:vendors, scope: :stalnoy_import) %></th>
  <th><%= Spree.t(:last_change_at, scope: :stalnoy_import) %></th>
  <th><%= Spree.t(:actions, scope: :stalnoy_import) %></th>
  <th><%= Spree.t(:rules, scope: :stalnoy_import) %></th>
  </thead>

  <tbody>



  <% if @stalnoy_imports.any? %>
      <% @stalnoy_imports.each do |import| %>
          <tr>
            <td><%= import.name %></td>
            <td><%= TimeDifference.between(Time.now.utc,import.updated_at).humanize %></td>
            <td><%= link_to_edit import %>
              <%= link_to_delete import %>

            </td>
            <td>
              <%= link_to Spree.t(:set_cols, scope: :stalnoy_import), admin_vcols_path(import),class:"btn btn-#{(import.cols.nil?)? 'danger': 'success'} btn-sm icon-link with-tip action-edit" %>
              <%= link_to Spree.t(:set_rows, scope: :stalnoy_import), admin_vrows_path(import),class:"btn btn-#{(import.rows.nil?)? 'warning': 'success'} btn-sm icon-link with-tip action-edit " %>
            </td>
          </tr>
      <% end %>
      </tbody>
      </table>
  <% else %>
      </tbody>
      </table>
      <div class="alert alert-warning no-objects-found">
        <%= Spree.t(:no_resource_found, resource: Spree::StalnoyImport.model_name.human) %>,
        <%= link_to Spree.t(:add_one), spree.new_admin_stalnoy_import_path %>!
      </div>
  <% end %>

  <script type="text/javascript" charset="utf-8">
      $( ".hash-event" ).click(function(e) {
          progress = 0;
          count = 0;
          key = $(e.currentTarget).attr('key');
          id = $(e.currentTarget).attr('hash');
          a = "#hash-bar-" + id.toString();
          if (typeof last_result !== 'undefined'){
              last_result == undefined;
          }
          if ($(e.currentTarget).attr('action') == 'put') {
              var eventSource = new EventSource('/admin/stalnoy_import_hide_all');
          }
          if ($(e.currentTarget).attr('action') == 'get') {

              var eventSource = new EventSource('/admin/stalnoy_import_hide_all');



          }


          eventSource.onopen = function(e) {
              console.log("Соединение открыто");
          };

          eventSource.onerror = function(e) {
              if (this.readyState == EventSource.CONNECTING) {
                  console.log("Соединение порвалось");
                  eventSource.close();
              } else {
                  console.log("Ошибка, состояние: " + this.readyState);
                  eventSource.close();
              }
          };

          eventSource.addEventListener('message', function(e) {
              console.log(e.data);
//        $('#out').append(e.data);
              resp = JSON.parse(e.data);

              if (resp.status == "work") {
                  //a = "#hash-bar-" + resp.id.toString();
                  bar = $('.progress[hash=' + resp.id.toString() +']')
                  a = $('.progress[hash=' + resp.id.toString() +']').children().last();
                  inc = 100 / resp.total;


                  if (typeof last_result === 'undefined')
                  {   last_result = resp.result
                      if (resp.result == true) {
                          a.addClass('progress-bar-warning');
                      } else
                      {
                          a.addClass('progress-bar-danger');
                      }
                      // progress = 0;
                      //count = 0;

                  }

                  if (last_result == resp.result) {

                      progress = progress + inc ;
                      a.css('width',progress.toString() + '%');
                      count++;
                      a.html(count.toString());


                  } else {
                      if (resp.result == true) {
                          bar.append('<div class="progress-bar progress-bar-warning" role="progressbar"></div>');
                      } else
                      {
                          bar.append('<div class="progress-bar progress-bar-danger" role="progressbar"></div>');
                      }
                      count=1;
                      progress = 0;
                      progress = progress + inc ;
                      a = $('.progress[hash=' + resp.id.toString() +']').children().last();
                      $(a).css('width',progress.toString() + '%');
                      a.html(count.toString());
                      last_result = resp.result;


                      //$('.progress[hash=8]').children().last().css('width','10%')
                      //$('.progress[hash=8]').append('<div class="progress-bar progress-bar-danger" role="progressbar" style="width:10%"></div>');
                  }



                  d = "#p-content-" + resp.id.toString();

                  // a = "#hash-bar-" + resp.id.toString();
                  progress_all = (resp.last_row /resp.total ) * 100;
                  //$(a).css('width',progress.toString() + '%');

                  text = "[ " + resp.last_row.toString() + " / " + resp.total.toString() + " ] " + progress_all.toString().substr(0, 5) +"% " + resp.hash + " <%= Spree.t(:preparing, scope: :stalnoy_import)%>";
                  $(d).html(text);



              }
              if (resp.status == "done") {
                  l = $('.progress[hash=' + resp.id.toString() +']').children().length - 1;
                  l = 100 / l;
                  $('.progress[hash=' + resp.id.toString() +']').children().not('.index').css('width', l.toString() + '%');
                  // d = "#p-content-" + resp.id.toString();
                  // p = "#vendor-name-" + resp.id.toString();
                  //  a = "#hash-bar-" + resp.id.toString();
                  progress = (resp.last_row /resp.total ) * 100;
                  //$(a).css('width',progress.toString() + '%');
                  text = "[ " + resp.last_row.toString() + " / " + resp.total.toString() + " ] " + progress.toString().substr(0, 5) +"% " + resp.hash + " <%= Spree.t(:done, scope: :stalnoy_import)%>";
                  $(d).html(text);

              }
              if (resp.status == "preparing") {
                  //a = "#hash-bar-" + resp.id.toString();
                  bar = $('.progress[hash=' + resp.id.toString() +']')
                  a = $('.progress[hash=' + resp.id.toString() +']').children().last();
                  inc = 100 / resp.total;


                  if (typeof last_result === 'undefined')
                  {   last_result = resp.result
                      if (resp.result == true) {
                          a.addClass('progress-bar-warning');
                      } else
                      {
                          a.addClass('progress-bar-danger');
                      }
                      // progress = 0;
                      //count = 0;

                  }

                  if (last_result == resp.result) {

                      progress = progress + inc ;
                      a.css('width',progress.toString() + '%');
                      count++;
                      a.html(count.toString());


                  } else {
                      if (resp.result == true) {
                          bar.append('<div class="progress-bar progress-bar-warning" role="progressbar"></div>');
                      } else
                      {
                          bar.append('<div class="progress-bar progress-bar-danger" role="progressbar"></div>');
                      }
                      count=1;
                      progress = 0;
                      progress = progress + inc ;
                      a = $('.progress[hash=' + resp.id.toString() +']').children().last();
                      $(a).css('width',progress.toString() + '%');
                      a.html(count.toString());
                      last_result = resp.result;


                      //$('.progress[hash=8]').children().last().css('width','10%')
                      //$('.progress[hash=8]').append('<div class="progress-bar progress-bar-danger" role="progressbar" style="width:10%"></div>');
                  }



                  d = "#p-content-" + resp.id.toString();

                  // a = "#hash-bar-" + resp.id.toString();
                  progress_all = (resp.last_row /resp.total ) * 100;
                  //$(a).css('width',progress.toString() + '%');

                  text = "[ " + resp.last_row.toString() + " / " + resp.total.toString() + " ] " + progress_all.toString().substr(0, 5) +"% " + resp.hash + " <%= Spree.t(:preparing, scope: :stalnoy_import)%>";
                  $(d).html(text);

              }

              if (resp.status == "error") {
                  $('#myModal').modal()
                  $('#modal-content').html(resp.content);
                  $('#modal-trace').html(resp.trace);
              }

          });
      });
  </script>


  <div class="modal" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p id="modal-content"></p>

          <p id="modal-trace"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


  <script type="text/javascript" charset="utf-8">
      (function(){
          $('.page-actions').removeClass('col-xs-8');
          $('.page-actions').addClass('col-xs-12');
      })();
  </script>

app/views/spree/admin/stalnoy_imports/new.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:new_vendor, scope: :stalnoy_import) %>
<% end %>

<%= render 'form', resource: @stalnoy_import %>

app/views/spree/admin/stalnoy_imports/rows.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:set_rows, scope: :stalnoy_import) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:back_to_resource_list,scope: :stalnoy_import, resource: plural_resource_name(Spree::StalnoyImport)), admin_stalnoy_imports_path, icon: 'arrow-left', class: 'btn-primary' %>
    <button id="but">Skip rows</button>
<% end %>
<% content_for :head do %>
    <%= stylesheet_link_tag "spree/backend/jquery.dataTables.min.css"%>
    <%= javascript_include_tag "spree/backend/jquery.dataTables.min.js"%>

<% end %>
<style>
    .skip_row {
        color: red;
        font-variant: small-caps;
        background-color: gray !important;
    }
</style>

<%= bootstrap_form_tag url: admin_setcols_path(@stalnoy_import), method: 'put', layout: :inline do |f| %>
    <%= f.text_field :item_code,label: "Артикул", value: @template["item_code"], class: "col_#{@template["item_code"]}" %>
    <%= f.text_field :price,label: "Цена",  value: @template["price"], class: "col_#{@template["price"]}" %>
    <%= f.text_field :available,label: "Наличие",  value: @template["available"], class: "col_#{@template["available"]}" %>
<% end %>

<%= bootstrap_form_tag url: admin_setrows_path(@stalnoy_import), method: 'put', layout: :inline do |f| %>
    <%= f.text_field :item_code,label: "Артикул",  value: @rules["item_code"] %>
    <%= f.text_field :price,label: "Цена",  value: @rules["price"] %>

    <%= f.text_field :available,label: "В наличии",  value: @rules["available"] %>
    <%= f.text_field :unavailable,label: "Отсутствует",  value: @rules["unavailable"] %>
    <%= f.text_field :on_order,label: "Под заказ",  value: @rules["on_order"] %>
    <%= f.text_field :white_space,label: "white space",  value: @rules["white_space"] %>
    <%= f.submit "Apply",layout: :horizontal %>
<% end %>

<table id="table" class="display" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th><%= @template["item_code"] %></th>
    <th><%= @template["price"] %></th>
    <th><%= @template["available"] %></th>
  </tr>
  </thead>

  <tfoot>
  <tr>
    <th><%= @template["item_code"] %></th>
    <th><%= @template["price"] %></th>
    <th><%= @template["available"] %></th>
  </tr>
  </tfoot>

  <tbody>
  <% @preset.each do |row| %>
      <% item_code_current_value = row[0] %>

      <% price_current_value = (row[1].nil?)? 0 : row[1]  %>

      <% available_current_value = row[2] %>
      <% if StalnoyRules.bool_and(@ruls_item_code,item_code_current_value) and StalnoyRules.bool_and(@ruls_price,price_current_value) and (StalnoyRules.bool_or(@ruls_available,available_current_value) or StalnoyRules.bool_or(@ruls_on_order,available_current_value) or StalnoyRules.bool_or(@ruls_unavailable,available_current_value) ) %>

          <tr>
            <td><%= item_code_current_value %></td>
            <td><%= price_current_value %></td>
            <td><%= available_current_value %></td>
          </tr>

      <% else %>
          <tr>
            <% row.each do |r| %>
                <td class="skip_row"><%= r %></td>
            <% end %>
          </tr>

      <% end %>

  <%end%>

  </tbody>
</table>




<script>
    function highlight () {
        if ("col_<%= @template["item_code"] %>".indexOf("col_") != -1 ) {
            $(".col_<%= @template["item_code"] %>").css("background-color","rgba(245, 241, 133, 0.65)");
        }
        if ("col_<%= @template["price"] %>".indexOf("col_") != -1 ) {
            $(".col_<%= @template["price"] %>").css("background-color","antiquewhite");
        }
        if ("col_<%= @template["currency"] %>".indexOf("col_") != -1 && "<%= @template["currency"] %>" !="$SOURCE" ) {
            $(".col_<%= @template["currency"] %>").css("background-color","khaki");
        }
        if ("col_<%= @template["available"] %>".indexOf("col_") != -1 ) {
            $(".col_<%= @template["available"] %>").css("background-color","lightgreen");
        }

    }



    //asd
    $(document).ready(function() {
        var i=0;
        var table = $('#table').DataTable({

            "iDisplayLength": -1,

            "createdRow": function ( row, data, index ) {
                $(row.cells).attr('index',i.toString());
                i++;
//
//                var ii=0;
//                $.each(row, function (a, value){
//
//
//                    $(row.cells[i]).addClass("col_"+(ii).toString());
//                    ii++;
//
//
//                    i++;
//                });
//                highlight();
            }});

        $('#table tbody').on( 'click', 'tr', function () {
            $(this).toggleClass('selected');
        } );

        $('#but').click( function () {
            var arr = table.rows('.selected').data();
            $('.selected').each(function() {
                if ( $( this ).hasClass( "skip_row" ) ) {
                    $(this).removeClass('skip_row');
                } else {
                    $(this).addClass('skip_row');
                }
            });
            $.each(arr, function(index, value) {
//            $.post( "<%#=url_for( controller: "stalnoy_import", action: "setrows", only_path: false  ) %>", { id: value[0] } );
                console.log(value[0]);
            });

        } );
    });



</script>

app/views/spree/admin/stalnoy_imports/rules.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:setup_rules, scope: :stalnoy_import) %>
<% end %>
<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:back_to_resource_list,scope: :stalnoy_import, resource: plural_resource_name(Spree::StalnoyImport)), spree.admin_stalnoy_imports_path, icon: 'arrow-left', class: 'btn-primary' %>


<%end%>
<table class="table">
  <thead>

  <th><%= Spree.t(:vendors, scope: :stalnoy_import) %></th>
  <th><%= Spree.t(:load_at, scope: :stalnoy_import) %></th>
  <th><%= Spree.t(:actions, scope: :stalnoy_import) %></th>
  </thead>

  <tbody>



  <% if @stalnoy_imports.any? %>
      <% @stalnoy_imports.each do |import| %>
          <tr>
            <td><%= import.name %></td>
            <td><%= import.updated_at %></td>
            <td><%= link_to Spree.t(:set_cols, scope: :stalnoy_import), admin_vcols_path(import),class:"btn btn-warning btn-sm icon-link with-tip action-edit" %>
              <%= link_to Spree.t(:set_rows, scope: :stalnoy_import), admin_vrows_path(import),class:"btn btn-danger btn-sm icon-link with-tip action-edit " %></td>
          </tr>
      <% end %>
      </tbody>
      </table>
  <% else %>
      </tbody>
      </table>
      <div class="alert alert-warning no-objects-found">
        <%= Spree.t(:no_resource_found, resource: Spree::SaleRate.model_name.human) %>,
        <%= link_to Spree.t(:add_one), spree.new_admin_stalnoy_import_path %>!
      </div>
  <% end %>